package exp.glorio.model.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import exp.glorio.model.data.Category;
import exp.glorio.model.data.Public;

import exp.glorio.model.data.CategoryDao;
import exp.glorio.model.data.PublicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig publicDaoConfig;

    private final CategoryDao categoryDao;
    private final PublicDao publicDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        publicDaoConfig = daoConfigMap.get(PublicDao.class).clone();
        publicDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        publicDao = new PublicDao(publicDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Public.class, publicDao);
    }
    
    public void clear() {
        categoryDaoConfig.clearIdentityScope();
        publicDaoConfig.clearIdentityScope();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public PublicDao getPublicDao() {
        return publicDao;
    }

}
